name: gnn
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.12.8
  - pytorch::pytorch==2.5.1
  - astartes==1.3.0
  - aimsim==2.2.2
  - configargparse==1.7
  - lightning==2.5.0.post0
  - numpy==1.26.4
  - pandas==2.2.3
  - rdkit==2024.09.5
  - scikit-learn==1.6.1
  - scipy==1.15.1
  - rich==13.9.4
  - descriptastorus==2.7.0.4
